language: python

python:
  - "3.6"

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip uninstall -y numpy

install:
  - pip install --only-binary=numpy -r requirements.txt
  - pip install --only-binary=numpy -r test_requirements.txt
  - pip install codecov

script:
  - python tests/test_imageredux.py -v
  - coverage run --source imageredux.py tests/test_imageredux.py

after_success:
  - codecov
